create or replace function
get_teachers(number int) 
returns table
(
	first_name text,
	last_name text,
	email text 
  
)as
$$
begin

return query
select 
   teacher.first_name, teacher.last_name, teacher.email 
from teacher
	join teacher_subject on teacher.id = teacher_subject.teacher_id
	join subject on teacher_subject.subject_id = subject.id
group by 
   teacher.first_name, teacher.last_name, teacher.email
having count(*) = number;

end;
$$
Language plpgsql;